### ISSUE TITLE
SMS only come if I restart the adapter

### ISSUE THREAD

**Issue by Dtrieb** [iobroker-community-adapters/ioBroker.gsmsms#10]
I have setup a new IOBroker System.
Everything works fine with my backup, only gsmsms v0.0.4 didn't work correct.

I set the right USB Port but the SMS only comes if I restart the adapter.
Set the "Abrufintervall (s)" to 5 seconds, but it didn't help.

**Comment by forelleblau** [comment]
My solution for this issue was to try different settings for these two parameters:
<img width="152" alt="image" src="https://github.com/forelleblau/ioBroker.gsmsms/assets/44144152/efae267a-ee81-406f-9365-faeb00a5c1d4">

**Comment by forelleblau** [comment]
Hi. Already checked this hint from 'README'? The log looks allright, the delivery - problem has to be solved with the correct settings for your Hardware.

**Comment by mcm1957** [comment]
If the problem still exists, please open a new issue and attach a log with instance log level set to DEBUG.
