### ISSUE TITLE
Move repository to iobroker-community-adapters

### ISSUE THREAD

**Issue by forelleblau** [iobroker-community-adapters/ioBroker.gsmsms#25]
Hallo Martin und Ingo @mcm1957 @Apollon77 
Ich würde den gsmsms - Adapter zu den community-adapters verschieben. Es ist leider so, dass ich immer weniger Zeit für meine Adapter aufwenden kann (und auch ein wenig 'will') und so der Rolle des maintainers definitv nicht mehr gerecht werden kann. Ich wäre daher froh, wenn ich - bei entsprechendem Interesse am Adapter eurerseits - diese Rolle künftig euch überlassen dürfte. Ingo, ich hab dich hier erwähnt, da wir beim Erstellen Kontakt hatten und du mich dabei unterstützt hast.
Ich werde auch meine anderen Adapter, die aber bereits in der community sind, so gut wie möglich auf den neuesten Stand bringen und dann jemanden suchen, der sich darum kümmert. Meldet euch bitte, wenn ich mit

1. send an github invite for transfer ownership to @mcm1957 a. Go to your GitHub repo that you want to move b. Settings -> Danger Zone -> Transfer Ownership c. Click on 'Transfer' d. Type 'mcm1957' as New owner
2. send a npm invite to add @mcm1957 for your adapter package a. log in at npmjs b. select your adapter c. select settings d. add "mcm1957" into field "invite maintainer" and press "invite"

Herzliche Grüsse
Marcel

**Comment by mcm1957** [comment]
Ich kann dne Transfer incl. der notwendigenb url Anpassunge jederzeit druchführen. Damit kann der Adapter gener in den Community Bereich kommen. Bitte wie du eh gefunden hat einfach mal einen Transfer zu mir auslösen - ich schiebs dann weiter.

Du behälts (außer du willst das definitiv nicht :-) ) jedenfalls Zugriff. Bits ja mW. sowieso in der community Orga wenn ich mich nicht irre.

Was Maintainence betrifft kann ich (persönlich) keine Zusage treffen da meine Taskliste lang ist. Aber ich bin sicher, dass sich wer findet wenn Probleme auftreten. Und insbesondere Anpassungen an js-cotroller 8 / 9 / 10 / 25 / 205 ...  sind zu 99,99% sichergestellt.

**Comment by mcm1957** [comment]
P.S. Falls das "will" oben irgendwie durch "uns" bewirkt oder verstärkt wird, besprich das ev. direkt und im 1:1 chat mit Ingo. Ist kein Thema für hier.

**Comment by forelleblau** [comment]
Nein, das 'will' oben entspringt einzig und allein meinen Lebensumständen. Ich habe mich in der Community immer gut aufgehoben und bei Bedarf super unterstützt gefühlt. Herzlichen Dank dafür! Den Transfer löse ich aus.

**Comment by mcm1957** [comment]
Danke für die Freigabe der MIgration. Repo ist migrietr - notwendige Anpassungen (urls, ...) erfolgen zeitnahe.
